# Generated by Django 5.2.17 on 2026-09-28 05:31

import django.db.models.deletion
import django.utils.timezone
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_award'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('participant', 'Certificate of participation'), ('award', "Winner's certificate"), ('judge', "Judge's record"), ('organizer', "Organizer's certificate")], max_length=12)),
                ('subject', models.CharField(max_length=40)),
                ('code', models.CharField(default=records.models.new_code, max_length=19, unique=True)),
                ('payload', models.TextField()),
                ('signature', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=16)),
                ('private', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='events.event')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('event', 'user', 'kind', 'subject'), name='one_live_record_per_subject')],
            },
        ),
    ]
