# Generated by Django 5.2.17 on 2026-09-27 13:20

import django.db.models.deletion
import django.utils.timezone
import voting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_eventrole_all_tracks'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=voting.models.new_token, max_length=48, unique=True)),
                ('kind', models.CharField(choices=[('link', 'Open link'), ('email', 'Email'), ('account', 'Account')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveSmallIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='voting.ballot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_entries', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=voting.models.default_pass_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text="Off means no ballot page, and the event page doesn't mention voting.", verbose_name='run a community vote')),
                ('access', models.CharField(choices=[('link', 'Open link'), ('email', 'Email-gated'), ('account', 'Signed in')], default='account', max_length=10, verbose_name='who can vote')),
                ('method', models.CharField(choices=[('quadratic', 'Quadratic voting'), ('single', 'One person, one vote')], default='quadratic', max_length=10)),
                ('credits', models.PositiveSmallIntegerField(default=25, help_text='Quadratic only. n votes on one project cost n × n credits.', verbose_name='credits per voter')),
                ('max_votes', models.PositiveSmallIntegerField(default=3, help_text='Quadratic only. Stops a group of friends going all-in on one project. 3 is the tested default.', verbose_name='most votes on one project')),
                ('opens_at', models.DateTimeField(blank=True, help_text='Leave empty to open when submissions close, so everyone votes on final projects.', null=True, verbose_name='voting opens')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='voting closes')),
                ('link_token', models.CharField(default=voting.models.new_token, max_length=48, unique=True)),
                ('email_domains', models.CharField(blank=True, help_text='Email-gated only. Comma separated, e.g. example.org, uni.edu. Leave empty to allow any address.', max_length=300, verbose_name='only these email domains')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_config', to='events.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='one_ballot_per_account'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('event', 'email'), name='one_ballot_per_email'),
        ),
        migrations.AddConstraint(
            model_name='ballotentry',
            constraint=models.UniqueConstraint(fields=('ballot', 'project'), name='one_entry_per_project_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='ballotentry',
            constraint=models.CheckConstraint(condition=models.Q(('votes__gte', 1)), name='ballot_entry_has_votes'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 1)), name='voting_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_votes__gte', 1)), name='voting_max_votes_positive'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='voting_closes_after_it_opens'),
        ),
    ]
