# Generated by Django 5.2.17 on 2026-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votingconfig_results_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingconfig',
            name='order',
            field=models.CharField(choices=[('shuffled', 'Shuffled for each voter'), ('alphabetical', 'A to Z')], default='shuffled', help_text='Shuffled gives every voter their own order, the same each time they come back, so no project gains from sitting at the top. A to Z hands the first few projects most of the votes.', max_length=12, verbose_name='ballot order'),
        ),
    ]
