# Generated by Django 5.2.17 on 2026-09-28 04:39

import django.db.models.deletion
import django.utils.timezone
import uuid
import webhooks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_alter_activity_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=140)),
                ('categories', models.CharField(default='all', max_length=200)),
                ('secret', models.CharField(default=webhooks.models.new_secret, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_streak', models.PositiveIntegerField(default=0)),
                ('disabled_reason', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='events.event')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('succeeded', 'Delivered'), ('failed', 'Gave up')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_excerpt', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.activity')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
