# Generated by Django 5.2.17 on 2026-09-27 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=240)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('short', 'Short answer'), ('long', 'Paragraph'), ('url', 'Link'), ('choice', 'Pick one'), ('yesno', 'Yes or no')], default='short', max_length=10)),
                ('options', models.TextField(blank=True, help_text="For 'Pick one': one option per line.")),
                ('required', models.BooleanField(default=False, help_text='Teams can save drafts without it, but not submit.')),
                ('is_public', models.BooleanField(default=True, help_text='Private answers are only seen by the team and organizers.', verbose_name='show in gallery')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Markdown: **bold**, _italic_, lists, links.')),
                ('location', models.CharField(blank=True, max_length=140)),
                ('timezone', models.CharField(default='UTC', help_text='Dates on the event page are shown in this time zone.', max_length=64)),
                ('starts_at', models.DateTimeField(help_text='Project editing opens at kickoff.', verbose_name='kickoff')),
                ('submissions_close_at', models.DateTimeField(help_text='After this moment nobody can create or change a project.', verbose_name='submission deadline')),
                ('judging_ends_at', models.DateTimeField(blank=True, null=True)),
                ('results_at', models.DateTimeField(blank=True, null=True, verbose_name='winners announced')),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished events are only visible to organizers.', verbose_name='published')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['-submissions_close_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('judge', 'Judge')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['role', 'user__name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, help_text='Free text, e.g. "$1,500" or "Mechanical keyboard".', max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='How many winners get this prize.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, max_length=40)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
