# Generated by Django 5.2.17 on 2026-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='all_tracks',
            field=models.BooleanField(default=False, help_text='Floaters can be assigned projects from any track.', verbose_name='can judge every track'),
        ),
    ]
