# Generated by Django 5.2.17 on 2026-09-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventrole_all_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments_enabled',
            field=models.BooleanField(default=True, help_text='Signed-in people can comment on projects in the gallery. Turn off to close every thread.', verbose_name='comments on projects'),
        ),
    ]
