# Generated by Django 5.2.17 on 2026-09-28 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_activity_event'),
        ('projects', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Optional. Why, in a line, for the certificate.', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.prize')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='projects.project')),
            ],
            options={
                'ordering': ['prize__position', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('prize', 'project'), name='one_award_per_prize_per_project')],
            },
        ),
    ]
