# Generated by Django 5.2.17 on 2026-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery_before_deadline',
            field=models.BooleanField(default=False, help_text="Off: submitted projects stay private to their team and the organizers until submissions close, so nobody can copy an early team's idea. On: they appear as soon as they're submitted.", verbose_name='show projects in the gallery before the deadline'),
        ),
    ]
