# Generated by Django 5.2.17 on 2026-09-27 09:18

import django.db.models.deletion
import django.utils.timezone
import judging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_eventrole_all_tracks'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('algorithmic', 'Algorithmic'), ('import', 'Imported')], default='algorithmic', max_length=12)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('target_reviews', models.PositiveSmallIntegerField(default=3)),
                ('shortfall_count', models.PositiveIntegerField(default=0)),
                ('shortfall_detail', models.TextField(blank=True, help_text='JSON: [[project id, reviews missing], ...]')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_batches', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'assignment batches',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='judging.assignmentbatch')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_conflicts', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_conflicts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_conflicts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Short name used in CSV columns and the API.', max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, help_text='What judges should look for. Shown next to the marks.', max_length=300)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text="Relative importance. Weights don't need to add up to anything.", max_digits=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.event')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=judging.models.new_invite_token, max_length=48, unique=True)),
                ('email', models.EmailField(blank=True, help_text='If given, only the account with this email can accept.', max_length=254)),
                ('all_tracks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=judging.models.default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_invites', to='events.event')),
                ('tracks', models.ManyToManyField(blank=True, related_name='+', to='events.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_min', models.PositiveSmallIntegerField(default=1, verbose_name='lowest mark')),
                ('scale_max', models.PositiveSmallIntegerField(default=5, verbose_name='highest mark')),
                ('reviews_per_project', models.PositiveSmallIntegerField(default=3, help_text='How many judges should score each project. Assignment batches fill up to this.', verbose_name='reviews per project')),
                ('kappa', models.FloatField(default=5.0, help_text="How many projects' worth of population spread every judge starts with. 5 is the tested default.", verbose_name='normalization strength (kappa)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judging_config', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('judge', 'Judge'), ('import', 'Imported')], default='judge', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='judging.assignment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_scores', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judging.criterion')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='judging.score')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_json', models.TextField(help_text='JSON: {criterion key: mark}')),
                ('comment', models.TextField(blank=True)),
                ('submitted', models.BooleanField(default=False)),
                ('source', models.CharField(default='judge', max_length=8)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='judging.score')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['event', 'judge'], name='assignment_event_judge'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='one_assignment_per_judge_and_project'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='one_conflict_row_per_judge_and_project'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='criterion_key_unique_per_event'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='criterion_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='judgingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('scale_max__gt', models.F('scale_min'))), name='judging_scale_is_a_range'),
        ),
        migrations.AddConstraint(
            model_name='judgingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('reviews_per_project__gte', 1)), name='judging_needs_a_review'),
        ),
        migrations.AddConstraint(
            model_name='judgingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('kappa__gte', 0)), name='judging_kappa_not_negative'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['event', 'submitted_at'], name='score_event_submitted'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='one_score_per_judge_and_project'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('score', 'criterion'), name='one_mark_per_criterion'),
        ),
    ]
