# Generated by Django 5.2.17 on 2026-09-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='let other sites embed the gallery')),
                ('allowed_origins', models.TextField(blank=True, help_text='One per line, like https://hackathon.example.org. Leave empty to allow any site.', verbose_name='only on these sites')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embed_settings', to='events.event')),
            ],
        ),
    ]
